=== christianurich/CityDrain3/data/dtd/model.dtd
<!ELEMENT citydrain (pluginpath*, simulation, controller*, model) >
<!ELEMENT model (nodelist, connectionlist) >
<!ELEMENT nodelist (node*) >
<!ELEMENT connectionlist (connection*) >
<!ELEMENT simulation (time, flowdefinition) >
<!ELEMENT flowdefinition (flow, concentration*) >
<!ELEMENT flow EMPTY >
<!ELEMENT concentration EMPTY >
<!ELEMENT time EMPTY >
<!ELEMENT pluginpath EMPTY >
<!ELEMENT node (parameter*) >
<!ELEMENT parameter ANY >
<!ELEMENT connection (source, sink) >
<!ELEMENT source EMPTY >
<!ELEMENT sink EMPTY >
<!ELEMENT unit EMPTY >
<!ELEMENT controller EMPTY >

<!ATTLIST citydrain 
	version CDATA #REQUIRED >
	
<!ATTLIST simulation
	class CDATA #REQUIRED >
	
<!ATTLIST node
	id ID #REQUIRED
	class CDATA #REQUIRED 
	script CDATA #IMPLIED >
	
<!ATTLIST time
	start CDATA #REQUIRED
	stop CDATA  #REQUIRED
	dt CDATA #REQUIRED >
	
<!ATTLIST concentration
	name CDATA #REQUIRED>
	
<!ATTLIST flow
	name CDATA #REQUIRED>
	
<!ATTLIST pluginpath
	path CDATA #REQUIRED >

<!ATTLIST controller
	script CDATA #REQUIRED >

<!ATTLIST parameter 
	name CDATA #REQUIRED
	type (string|bool|float|double|int|flow) #REQUIRED
	value CDATA #IMPLIED >
	
<!ATTLIST connection
	id ID #REQUIRED
	cycle_break (true|false) #IMPLIED >
	
<!ATTLIST sink
	node IDREF #REQUIRED
	port CDATA #REQUIRED >
	
<!ATTLIST source
	node IDREF #REQUIRED
	port CDATA #REQUIRED >

<!ATTLIST unit
	name CDATA #REQUIRED
	kind (Flow|Rain|Concentration|Volume) #REQUIRED
	value CDATA #REQUIRED >

=== christianurich/CityDrain3/models/test-rainread.xml
<?xml version="1.0"?>
<!DOCTYPE citydrain SYSTEM "model.dtd">

<citydrain version="1.0">

	<pluginpath path="./libnodes.so.1.0.0" />

	<simulation class="VarDTSimulation">
		<time start="0" stop="72000" dt="300" />
	</simulation>

	<model>
		<nodelist>
			<node id="rainread0" class="RainRead">
				<parameter name="file_name" type="string" value="models/Station_6620.ixx" />
			</node>
			
			<node id="fileout" class="FileOut">
				<parameter name="out_file_name" type="string" value="test-rainread.txt" />
			</node>
		</nodelist>
		
		<connectionlist>
			<connection id="con1">
				<source node="rainread0" port="out" />
				<sink	node="fileout" port="in" />
			</connection>
		</connectionlist>
	</model>
</citydrain>

=== christianurich/CityDrain3/data/models/test-python.xml
<?xml version="1.0"?>
<!DOCTYPE citydrain SYSTEM "../dtd/model.dtd">

<citydrain version="1.0">

	<pluginpath path="nodes" />
	<pythonmodule module="cdtest" />

	<simulation class="DefaultSimulation">
		<time start="0" stop="72000" dt="300" />
	</simulation>

	<model>
		<nodelist>
			<node id="constsource" class="ConstSource">
				<parameter name="const_flow" kind="complex" type="Flow">
					<flow>
						<unit name="Q" kind="Flow" value="234.0" />
						<unit name="C0" kind="Concentration" value="0.1"/>
						<unit name="C1" kind="Concentration" value="0.2"/>
					</flow>
				</parameter>
			</node>
			
			<node id="fileout" class="FileOut">
				<parameter name="out_file_name" type="string" 
						value="tmp/pythonout.txt" />
			</node>
			
			<node id="musk1" class="Sewer" />
			
			<node id="pynode" class="MichiPythonNode" />
			
		</nodelist>
		
		<connectionlist>
		
			<connection id="con1">
				<source node="constsource" port="out" />
				<sink	node="musk1" port="in" />
			</connection>
			
			<connection id="con3">
				<source node="musk1" port="out" />
				<sink node="pynode" port="in" />
			</connection>
			
			<connection id="con2">
				<source node="pynode" port="out" />
				<sink node="fileout" port="in" />
			</connection>
			
		</connectionlist>
	</model>
</citydrain>

=== christianurich/CityDrain3/data/models/gl_test-catchment.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE citydrain SYSTEM "file:../dtd/model.dtd">

<citydrain version="1.0">

	<pluginpath path="nodes" />

	<simulation class="DefaultSimulation">
		<time start="0" stop="86400" dt="60" />
		<flowdefinition>
		    <flow name="Q"/>
		    <concentration name="C0"/>
		    <concentration name="C1"/>
		    <concentration name="C2"/>
		</flowdefinition>
	</simulation>

	<model>
		<nodelist>
			<node id="RainRead" class="RainRead">
				<parameter name="file_name" type="string" value="data/models/gl_testrain_24h15min.ixx" />
			</node>
			
			<node id="CatchmentCSS" class="CatchmentCSS">
				<parameter name="area" type="int" value="10000" />
				<parameter name="run_off_coeff" type="double" value="1.0" />
				<parameter name="initial_loss" type="double" value="2.0" />
				<parameter name="permanent_loss" type="double" value="1.0" />
				<parameter name="N" type="int" value="1" />
				<parameter name="K" type="double" value="120.0" />
				<parameter name="X" type="double" value="0.0" />
			</node>
			
			<node id="FileOut" class="FileOut">
				<parameter name="out_file_name" type="string" value="tmp/gl_test_catchment.txt" />
			</node>
		</nodelist>
		
		<connectionlist>
			<connection id="con-RainRead-CatchmentCSS">
				<source node="RainRead" port="out" />
				<sink node="CatchmentCSS" port="rain_in" />
			</connection>


			<connection id="con-CatchmentCSS-FileOut">
				<source node="CatchmentCSS" port="out" />
				<sink node="FileOut" port="in" />
			</connection>

		</connectionlist>
	</model>
</citydrain>

=== christianurich/CityDrain3/models/test-vardt.xml
<?xml version="1.0"?>
<!DOCTYPE citydrain SYSTEM "model.dtd">

<citydrain version="1.0">

	<pluginpath path="nodes/libnodes.so.1.0.0" />

	<simulation class="VarDTSimulation">
		<time start="0" stop="7200" dt="300" />
	</simulation>

	<model>
		<nodelist>
			<node id="constsource" class="ConstSource">
				<parameter name="const_flow" kind="complex" type="Flow">
					<flow>
						<unit name="Q" kind="Flow" value="3.0" />
						<unit name="Scheiss Grusigs Michi" kind="Concentration" value="0.0"/>
						<unit name="Ei" kind="Concentration" value="10.0"/>
					</flow>
				</parameter>
			</node>
			
			<node id="fileout" class="FileOut">
				<parameter name="out_file_name" type="string" value="tmp/test-vardt.txt" />
			</node>
		</nodelist>
		
		<connectionlist>
			<connection id="con1">
				<source node="constsource" port="out" />
				<sink	node="fileout" port="in" />
			</connection>
		</connectionlist>
	</model>
</citydrain>

=== christianurich/CityDrain3/data/models/testpythonnodes.xml
<?xml version="1.0"?>
<!DOCTYPE citydrain SYSTEM "../dtd/model.dtd">

<citydrain version="1.0">

	<pluginpath path="nodes" />
	<pythonmodule module="testnodes" />

	<simulation class="DefaultSimulation">
		<time start="0" stop="72000" dt="300" />
		<flowdefinition>
		    <flow name="Q" />
            <concentration name="C0" />
            <concentration name="C1" />
		</flowdefinition>
	</simulation>

	<model>
		<nodelist>
			<node id="source" class="RandomCatchment"/>
			
			<node id="fileout" class="FileOut">
				<parameter name="out_file_name" type="string" 
						value="tmp/randomnout.txt" />
			</node>
			
			<node id="musk1" class="Sewer" />
			
		</nodelist>
		
		<connectionlist>
		
			<connection id="con1">
				<source node="source" port="out" />
				<sink	node="musk1" port="in" />
			</connection>
			
			<connection id="con3">
				<source node="musk1" port="out" />
				<sink node="fileout" port="in" />
			</connection>
			
		</connectionlist>
	</model>
</citydrain>

=== christianurich/CityDrain3/models/test-cso.xml
<?xml version="1.0"?>
<!DOCTYPE citydrain SYSTEM "../dtd/model.dtd">

<citydrain version="1.0">

	<pluginpath path="nodes" />

	<simulation class="OrderedPipeSimulation">
		<time start="0" stop="7200" dt="300" />
	</simulation>

	<model>
		<nodelist>
			<node id="constsource" class="ConstSource">
				<parameter name="const_flow" kind="complex" type="Flow">
					<flow>
							<unit name="Q" kind="Flow" value="12.0" />
						<unit name="C0" kind="Concentration" value="0.1"/>
						<unit name="C1" kind="Concentration" value="0.2"/>
					</flow>
				</parameter>
			</node>
			
			
			
			<node id="cso-out" class="FileOut">
				<parameter name="out_file_name" type="string" value="tmp/cso-out.txt" />
			</node>
			
			<node id="cso-overflow" class="FileOut">
				<parameter name="out_file_name" type="string" value="tmp/cso-overflow.txt" />
			</node>
			
			<node id="cso" class="CSO">
				<parameter name="Q_Max" type="double" value="10.0" />
				<parameter name="V_Max" type="double" value="30.0" />
			</node>
			
			<node id="sewer" class="Sewer" />
			
		</nodelist>
		
		<connectionlist>
		
			<connection id="con1">
				<source node="constsource" port="out" />
				<sink	node="cso" port="in" />
			</connection>
						
			<connection id="con2">
				<source node="sewer" port="out" />
				<sink node="cso-out" port="in" />
			</connection>
			
			<connection id="con4">
				<source node="cso" port="out" />
				<sink node="sewer" port="in" />
			</connection>
			
			<connection id="con3">
				<source node="cso" port="overflow" />
				<sink node="cso-overflow" port="in" />
			</connection>
			
		</connectionlist>
	</model>
</citydrain>

=== christianurich/CityDrain3/models/test.xml
<?xml version="1.0"?>
<!DOCTYPE citydrain SYSTEM "model.dtd">

<citydrain version="1.0">

	<pluginpath path="./libnodes.so" />
	<simulation class="DefaultSimulation">
		<time start="0" stop="7200" dt="300" />
	</simulation>
	<model>
		<nodelist>

			<node id="n-96c907ea-f517-4bd3-9c76-b189c080a760" class="Sewer">
			</node>


			<node id="n-7acc1846-7d4f-48c6-8f9a-6640296ded54" class="Sewer">
			</node>


			<node id="n-25097474-1d81-4784-bef2-a7025c0cb35d" class="ConstSource">
				<parameter name="const_flow" kind="complex" type="Flow">
					<flow>
						<unit name="Q" kind="Flow" value="100.000000" />
						<unit name="C2" kind="Concentration" value="3.000000" />
						<unit name="C1" kind="Concentration" value="5.000000" />
						<unit name="C0" kind="Concentration" value="1.000000" />
					</flow>
				</parameter>
			</node>


			<node id="n-1a65c028-eb0f-4577-b02e-33f00affa099" class="ConstSource">
				<parameter name="const_flow" kind="complex" type="Flow">
					<flow>
						<unit name="Q" kind="Flow" value="100.000000" />
						<unit name="C2" kind="Concentration" value="3.000000" />
						<unit name="C1" kind="Concentration" value="5.000000" />
						<unit name="C0" kind="Concentration" value="1.000000" />
					</flow>
				</parameter>
			</node>


			<node id="n-1667ae05-fe51-47c8-8a19-aa8fd775ace5" class="Mixer">
				<parameter name="num_inputs" type="int" value="2" />
			</node>


			<node id="n-6ead3015-36b4-4dec-a31c-493ad3b82e23" class="FileOut">
				<parameter name="out_file_name" type="string" value="tmp/test-gen-out.txt" />
			</node>

		</nodelist>
		<connectionlist>

			<connection id="con-n-25097474-1d81-4784-bef2-a7025c0cb35d-n-96c907ea-f517-4bd3-9c76-b189c080a760">
				<source node="n-25097474-1d81-4784-bef2-a7025c0cb35d" port="out" />
				<sink node="n-96c907ea-f517-4bd3-9c76-b189c080a760" port="in" />
			</connection>


			<connection id="con-n-1a65c028-eb0f-4577-b02e-33f00affa099-n-7acc1846-7d4f-48c6-8f9a-6640296ded54">
				<source node="n-1a65c028-eb0f-4577-b02e-33f00affa099" port="out" />
				<sink node="n-7acc1846-7d4f-48c6-8f9a-6640296ded54" port="in" />
			</connection>


			<connection id="con-n-25097474-1d81-4784-bef2-a7025c0cb35d-n-1667ae05-fe51-47c8-8a19-aa8fd775ace5">
				<source node="n-25097474-1d81-4784-bef2-a7025c0cb35d" port="out" />
				<sink node="n-1667ae05-fe51-47c8-8a19-aa8fd775ace5" port="inputs[0]" />
			</connection>


			<connection id="con-n-1a65c028-eb0f-4577-b02e-33f00affa099-n-1667ae05-fe51-47c8-8a19-aa8fd775ace5">
				<source node="n-1a65c028-eb0f-4577-b02e-33f00affa099" port="out" />
				<sink node="n-1667ae05-fe51-47c8-8a19-aa8fd775ace5" port="inputs[1]" />
			</connection>


			<connection id="con-n-1667ae05-fe51-47c8-8a19-aa8fd775ace5-n-6ead3015-36b4-4dec-a31c-493ad3b82e23">
				<source node="n-1667ae05-fe51-47c8-8a19-aa8fd775ace5" port="out" />
				<sink node="n-6ead3015-36b4-4dec-a31c-493ad3b82e23" port="in" />
			</connection>

		</connectionlist>
	</model>
</citydrain>
