=== christianurich/CityDrain3/data/dtd/model.dtd
<!ELEMENT citydrain (pluginpath*, simulation, controller*, model) >
<!ELEMENT model (nodelist, connectionlist) >
<!ELEMENT nodelist (node*) >
<!ELEMENT connectionlist (connection*) >
<!ELEMENT simulation (time, flowdefinition) >
<!ELEMENT flowdefinition (flow, concentration*) >
<!ELEMENT flow EMPTY >
<!ELEMENT concentration EMPTY >
<!ELEMENT time EMPTY >
<!ELEMENT pluginpath EMPTY >
<!ELEMENT node (parameter*) >
<!ELEMENT parameter ANY >
<!ELEMENT connection (source, sink) >
<!ELEMENT source EMPTY >
<!ELEMENT sink EMPTY >
<!ELEMENT unit EMPTY >
<!ELEMENT controller EMPTY >

<!ATTLIST citydrain 
	version CDATA #REQUIRED >
	
<!ATTLIST simulation
	class CDATA #REQUIRED >
	
<!ATTLIST node
	id ID #REQUIRED
	class CDATA #REQUIRED 
	script CDATA #IMPLIED >
	
<!ATTLIST time
	start CDATA #REQUIRED
	stop CDATA  #REQUIRED
	dt CDATA #REQUIRED >
	
<!ATTLIST concentration
	name CDATA #REQUIRED>
	
<!ATTLIST flow
	name CDATA #REQUIRED>
	
<!ATTLIST pluginpath
	path CDATA #REQUIRED >

<!ATTLIST controller
	script CDATA #REQUIRED >

<!ATTLIST parameter 
	name CDATA #REQUIRED
	type (string|bool|float|double|int|flow) #REQUIRED
	value CDATA #IMPLIED >
	
<!ATTLIST connection
	id ID #REQUIRED
	cycle_break (true|false) #IMPLIED >
	
<!ATTLIST sink
	node IDREF #REQUIRED
	port CDATA #REQUIRED >
	
<!ATTLIST source
	node IDREF #REQUIRED
	port CDATA #REQUIRED >

<!ATTLIST unit
	name CDATA #REQUIRED
	kind (Flow|Rain|Concentration|Volume) #REQUIRED
	value CDATA #REQUIRED >

=== christianurich/CityDrain3/models/test-qjs.xml
<?xml version="1.0"?>
<!DOCTYPE citydrain SYSTEM "model.dtd">

<citydrain version="1.0">

	<pluginpath path="./libnodes.so.1.0.0" />

	<simulation class="DefaultSimulation">
		<time start="0" stop="7200" dt="300" />
	</simulation>

	<model>
		<nodelist>
			<node id="constsource" class="ConstSource">
				<parameter name="const_flow" kind="complex" type="Flow">
					<flow>
						<unit name="Q" kind="Flow" value="1.0" />
						<unit name="nix da" kind="Concentration" value="0.1"/>
						<unit name="nix boese sein" kind="Concentration" value="0.2"/>
					</flow>
				</parameter>
			</node>
			
			<node id="fileout" class="FileOut">
				<parameter name="out_file_name" type="string" value="tmp/jsout.txt" />
			</node>
			
			<node id="js1" class="QSWNode" script="scripts/qscript.js">

			</node>
			
		</nodelist>
		
		<connectionlist>
		
			<connection id="con1">
				<source node="constsource" port="out" />
				<sink	node="js1" port="in" />
			</connection>
			
			<connection id="con2">
				<source node="js1" port="out" />
				<sink node="fileout" port="in" />
			</connection>
			
		</connectionlist>
	</model>
</citydrain>

=== christianurich/CityDrain3/data/models/test-cycle.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE citydrain SYSTEM "file:../dtd/model.dtd">

<citydrain version="1.0">

	<pluginpath path="nodes" />
	<simulation class="DefaultSimulation">
		<time start="0" stop="7200" dt="300" />
		<flowdefinition>
		    <flow name="Q"/>
		    <concentration name="C0"/>
		    <concentration name="C1"/>
		    <concentration name="C2"/>
		</flowdefinition>
	</simulation>
	<model>
		<nodelist>

			<node id="ConstSource-0" class="ConstSource">
				<parameter name="const_flow" kind="complex" type="Flow">
					<flow>
						<unit name="Q" value="100.000000" />
						<unit name="C2" value="3.000000" />
						<unit name="C1" value="5.000000" />
						<unit name="C0" value="1.000000" />
					</flow>
				</parameter>
			</node>


			<node id="Mixer-0" class="Mixer">
				<parameter name="num_inputs" type="int" value="2" />
			</node>


			<node id="Splitter-0" class="Splitter">
				<parameter name="ratio" type="double" value="0.5" />
			</node>


			<node id="FileOut-0" class="FileOut">
				<parameter name="out_file_name" type="string" 
					value="tmp/genout.txt" />
			</node>


			<node id="Sewer-0" class="Sewer">
				<parameter name="N" type="int" value="11" />
				<parameter name="K" type="int" value="300" />
				<parameter name="X" type="double" value="0.1" />
			</node>


			<node id="Sewer-1" class="Sewer">
				<parameter name="N" type="int" value="11" />
				<parameter name="K" type="int" value="300" />
				<parameter name="X" type="double" value="0.1" />
			</node>

		</nodelist>
		<connectionlist>

			<connection id="con-ConstSource-0-Mixer-0">
				<source node="ConstSource-0" port="out" />
				<sink node="Mixer-0" port="inputs[0]" />
			</connection>


			<connection id="con-Mixer-0-Splitter-0">
				<source node="Mixer-0" port="out" />
				<sink node="Splitter-0" port="in" />
			</connection>


			<connection id="con-Splitter-0-Sewer-0">
				<source node="Splitter-0" port="out1" />
				<sink node="Sewer-0" port="in" />
			</connection>


			<connection id="con-Splitter-0-Sewer-1">
				<source node="Splitter-0" port="out2" />
				<sink node="Sewer-1" port="in" />
			</connection>


			<connection id="con-Sewer-1-Mixer-0" cycle_break="true">
				<source node="Sewer-1" port="out" />
				<sink node="Mixer-0" port="inputs[1]" />
			</connection>


			<connection id="con-Sewer-0-FileOut-0">
				<source node="Sewer-0" port="out" />
				<sink node="FileOut-0" port="in" />
			</connection>

		</connectionlist>
	</model>
</citydrain>

=== christianurich/CityDrain3/models/complex.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE citydrain SYSTEM "file:../dtd/model.dtd">

<citydrain version="1.0">

	<pluginpath path="nodes" />
	<simulation class="OrderedPipeSimulation">
		<time start="0" stop="7200" dt="300" />
	</simulation>
	<model>
		<nodelist>

			<node id="ConstSource-0" class="ConstSource">
				<parameter name="const_flow" kind="complex" type="Flow">
					<flow>
						<unit name="Q" kind="Flow" value="100.000000" />
						<unit name="C2" kind="Concentration" value="3.000000" />
						<unit name="C1" kind="Concentration" value="5.000000" />
						<unit name="C0" kind="Concentration" value="1.000000" />
					</flow>
				</parameter>
			</node>


			<node id="ConstSource-1" class="ConstSource">
				<parameter name="const_flow" kind="complex" type="Flow">
					<flow>
						<unit name="Q" kind="Flow" value="100.000000" />
						<unit name="C2" kind="Concentration" value="3.000000" />
						<unit name="C1" kind="Concentration" value="5.000000" />
						<unit name="C0" kind="Concentration" value="1.000000" />
					</flow>
				</parameter>
			</node>


			<node id="Mixer-0" class="Mixer">
				<parameter name="num_inputs" type="int" value="2" />
			</node>


			<node id="Sewer-0" class="Sewer">
				<parameter name="N" type="int" value="11" />
				<parameter name="K" type="int" value="300" />
				<parameter name="X" type="double" value="0.1" />
			</node>


			<node id="Splitter-0" class="Splitter">
				<parameter name="ratio" type="double" value="0.2" />
			</node>


			<node id="Sewer-1" class="Sewer">
				<parameter name="N" type="int" value="11" />
				<parameter name="K" type="int" value="300" />
				<parameter name="X" type="double" value="0.1" />
			</node>


			<node id="Sewer-2" class="Sewer">
				<parameter name="N" type="int" value="11" />
				<parameter name="K" type="int" value="300" />
				<parameter name="X" type="double" value="0.1" />
			</node>


			<node id="FileOut-0" class="FileOut">
				<parameter name="out_file_name" type="string" value="tmp/comp1-out.txt" />
			</node>


			<node id="FileOut-1" class="FileOut">
				<parameter name="out_file_name" type="string" value="tmp/comp2-out.txt" />
			</node>

		</nodelist>
		<connectionlist>

			<connection id="con-ConstSource-0-Mixer-0">
				<source node="ConstSource-0" port="out" />
				<sink node="Mixer-0" port="inputs[0]" />
			</connection>


			<connection id="con-ConstSource-1-Mixer-0">
				<source node="ConstSource-1" port="out" />
				<sink node="Mixer-0" port="inputs[1]" />
			</connection>


			<connection id="con-Mixer-0-Sewer-0">
				<source node="Mixer-0" port="out" />
				<sink node="Sewer-0" port="in" />
			</connection>


			<connection id="con-Sewer-0-Splitter-0">
				<source node="Sewer-0" port="out" />
				<sink node="Splitter-0" port="in" />
			</connection>


			<connection id="con-Splitter-0-Sewer-1">
				<source node="Splitter-0" port="out1" />
				<sink node="Sewer-1" port="in" />
			</connection>


			<connection id="con-Splitter-0-Sewer-2">
				<source node="Splitter-0" port="out2" />
				<sink node="Sewer-2" port="in" />
			</connection>


			<connection id="con-Sewer-1-FileOut-0">
				<source node="Sewer-1" port="out" />
				<sink node="FileOut-0" port="in" />
			</connection>


			<connection id="con-Sewer-2-FileOut-1">
				<source node="Sewer-2" port="out" />
				<sink node="FileOut-1" port="in" />
			</connection>

		</connectionlist>
	</model>
</citydrain>

=== christianurich/CityDrain3/data/models/test-rainread.xml
<?xml version="1.0"?>
<!DOCTYPE citydrain SYSTEM "model.dtd">

<citydrain version="1.0">

	<pluginpath path="nodes" />

	<simulation class="DefaultSimulation">
		<time start="0" stop="86400" dt="50" />
	</simulation>

	<model>
		<nodelist>
			<node id="rainread0" class="RainRead">
				<parameter name="file_name" type="string" value="data/models/Station_6620.ixx" />
			</node>
			
			<node id="fileout" class="FileOut">
				<parameter name="out_file_name" type="string" value="test-rainread.txt" />
			</node>
		</nodelist>
		
		<connectionlist>
			<connection id="con1">
				<source node="rainread0" port="out" />
				<sink	node="fileout" port="in" />
			</connection>
		</connectionlist>
	</model>
</citydrain>

=== christianurich/CityDrain3/data/models/test-splitter.xml
<?xml version="1.0"?>
<!DOCTYPE citydrain SYSTEM "model.dtd">

<citydrain version="1.0">

	<pluginpath path="nodes" />

	<simulation class="DefaultSimulation">
		<time start="0" stop="7200" dt="300" />
	</simulation>

	<model>
		<nodelist>
			<node id="constsource" class="ConstSource">
				<parameter name="const_flow" kind="complex" type="Flow">
					<flow>
							<unit name="Q" kind="Flow" value="12.0" />
						<unit name="C0" kind="Concentration" value="0.1"/>
						<unit name="C1" kind="Concentration" value="0.2"/>
					</flow>
				</parameter>
			</node>
			
			
			
			<node id="out1" class="FileOut">
				<parameter name="out_file_name" type="string" value="tmp/split-out1.txt" />
			</node>
			
			<node id="out2" class="FileOut">
				<parameter name="out_file_name" type="string" value="tmp/split-out2.txt" />
			</node>
			
			<node id="splitter" class="Splitter">
				<parameter name="ratio" type="float" value="0.3333333" />
			</node>
			
		</nodelist>
		
		<connectionlist>
		
			<connection id="con1">
				<source node="constsource" port="out" />
				<sink	node="splitter" port="in" />
			</connection>
						
			<connection id="con2">
				<source node="splitter" port="out1" />
				<sink node="out1" port="in" />
			</connection>
			
			<connection id="con3">
				<source node="splitter" port="out2" />
				<sink node="out2" port="in" />
			</connection>
			
		</connectionlist>
	</model>
</citydrain>

=== christianurich/CityDrain3/data/models/test-random-python.xml
<?xml version="1.0"?>
<!DOCTYPE citydrain SYSTEM "../dtd/model.dtd">

<citydrain version="1.0">

	<pluginpath path="nodes" />
	<pythonmodule module="cdtest" />
	<pythonmodule module="testnodes" />

	<simulation class="DefaultSimulation">
		<time start="0" stop="72000" dt="300" />
		<flowdefinition>
		    <flow name="Q" />
            <concentration name="C0" />
            <concentration name="C1" />
		</flowdefinition>
	</simulation>

	<model>
		<nodelist>
			<node id="constsource1" class="RandomCatchment"/>
			<node id="constsource2" class="RandomCatchment"/>
			<node id="constsource3" class="RandomCatchment"/>
			
			<node id="fileout" class="FileOut">
				<parameter name="out_file_name" type="string" 
						value="tmp/test-random.txt" />
			</node>
			
			<node id="mixer" class="PyMixer">
			    <parameter name="count" type="int" value="3" />
			</node>
			
			<node id="musk1" class="Sewer" />
			
			<node id="pynode" class="MichiPythonNode">
				<parameter name="x" type="int" value="42"/>
			</node>
			
		</nodelist>
		
		<connectionlist>
		
			<connection id="con1">
				<source node="constsource1" port="out" />
				<sink	node="mixer" port="in0" />
			</connection>

			<connection id="con4">
				<source node="constsource2" port="out" />
				<sink	node="mixer" port="in1" />
			</connection>
			
			<connection id="con6">
				<source node="constsource3" port="out" />
				<sink	node="mixer" port="in2" />
			</connection>
			
			
            <connection id="con5">
				<source node="mixer" port="out" />
				<sink	node="musk1" port="in" />
			</connection>
			
			<connection id="con3">
				<source node="musk1" port="out" />
				<sink node="pynode" port="in" />
			</connection>
			
			<connection id="con2">
				<source node="pynode" port="out" />
				<sink node="fileout" port="in" />
			</connection>
			
		</connectionlist>
	</model>
</citydrain>

=== christianurich/CityDrain3/data/models/test-simple-python.xml
<?xml version="1.0"?>
<!DOCTYPE citydrain SYSTEM "../dtd/model.dtd">

<citydrain version="1.0">

	<pluginpath path="nodes" />
	<pythonmodule module="cdtest" />
	<pythonmodule module="testnodes" />

	<simulation class="DefaultSimulation">
		<time start="0" stop="72000" dt="300" />
		<flowdefinition>
		    <flow name="Q" />
            <concentration name="C0" />
            <concentration name="C1" />
		</flowdefinition>
	</simulation>

	<model>
		<nodelist>
			<node id="constsource1" class="RandomCatchment"/>
			
			<node id="fileout" class="PyOut">
				<parameter name="out" type="string" 
						value="tmp/test-random.txt" />
			</node>
		</nodelist>
		
		<connectionlist>
		
			<connection id="con1">
				<source node="constsource1" port="out" />
				<sink	node="fileout" port="in" />
			</connection>
		</connectionlist>
	</model>
</citydrain>

=== christianurich/CityDrain3/models/mixer.xml
<?xml version="1.0"?>
<!DOCTYPE citydrain SYSTEM "model.dtd">

<citydrain version="1.0">

	<pluginpath path="./libnodes.so.1.0.0" />

	<simulation class="DefaultSimulation">
		<time start="0" stop="7200" dt="300" />
	</simulation>

	<model>
		<nodelist>
			<node id="constsource1" class="ConstSource">
				<parameter name="const_flow" kind="complex" type="Flow">
					<flow>
						<unit name="Q" kind="Flow" value="100.0" />
						<unit name="C0" kind="Concentration" value="1.0" />
						<unit name="C1" kind="Concentration" value="2.0" />
						<unit name="C3" kind="Concentration" value="6.0" />
					</flow>
				</parameter>
			</node>
			
			<node id="constsource2" class="ConstSource">
				<parameter name="const_flow" kind="complex" type="Flow">
					<flow>
						<unit name="Q" kind="Flow" value="100.0" />
						<unit name="C0" kind="Concentration" value="1.0" />
						<unit name="C1" kind="Concentration" value="2.0" />
					</flow>
				</parameter>
			</node>
			
			<node id="mixer" class="Mixer">
				<parameter name="num_inputs" value="2" type="int" />
			</node>
			
			<node id="fileout" class="FileOut">
				<parameter name="out_file_name" type="string" value="tmp/mixer-out.txt" />
			</node>
		</nodelist>
		
		<connectionlist>
			<connection id="con1-mixer">
				<source node="constsource1" port="out" />
				<sink	node="mixer" port="inputs[0]" />
			</connection>
			
			<connection id="con2-mixer">
				<source node="constsource2" port="out" />
				<sink	node="mixer" port="inputs[1]" />
			</connection>
			
			<connection id="mixer-fileout">
				<source node="mixer" port="out" />
				<sink	node="fileout" port="in" />
			</connection>
		</connectionlist>
	</model>
</citydrain>
