=== christianurich/CityDrain3/data/dtd/model.dtd
<!ELEMENT citydrain (pluginpath*, simulation, controller*, model) >
<!ELEMENT model (nodelist, connectionlist) >
<!ELEMENT nodelist (node*) >
<!ELEMENT connectionlist (connection*) >
<!ELEMENT simulation (time, flowdefinition) >
<!ELEMENT flowdefinition (flow, concentration*) >
<!ELEMENT flow EMPTY >
<!ELEMENT concentration EMPTY >
<!ELEMENT time EMPTY >
<!ELEMENT pluginpath EMPTY >
<!ELEMENT node (parameter*) >
<!ELEMENT parameter ANY >
<!ELEMENT connection (source, sink) >
<!ELEMENT source EMPTY >
<!ELEMENT sink EMPTY >
<!ELEMENT unit EMPTY >
<!ELEMENT controller EMPTY >

<!ATTLIST citydrain 
	version CDATA #REQUIRED >
	
<!ATTLIST simulation
	class CDATA #REQUIRED >
	
<!ATTLIST node
	id ID #REQUIRED
	class CDATA #REQUIRED 
	script CDATA #IMPLIED >
	
<!ATTLIST time
	start CDATA #REQUIRED
	stop CDATA  #REQUIRED
	dt CDATA #REQUIRED >
	
<!ATTLIST concentration
	name CDATA #REQUIRED>
	
<!ATTLIST flow
	name CDATA #REQUIRED>
	
<!ATTLIST pluginpath
	path CDATA #REQUIRED >

<!ATTLIST controller
	script CDATA #REQUIRED >

<!ATTLIST parameter 
	name CDATA #REQUIRED
	type (string|bool|float|double|int|flow) #REQUIRED
	value CDATA #IMPLIED >
	
<!ATTLIST connection
	id ID #REQUIRED
	cycle_break (true|false) #IMPLIED >
	
<!ATTLIST sink
	node IDREF #REQUIRED
	port CDATA #REQUIRED >
	
<!ATTLIST source
	node IDREF #REQUIRED
	port CDATA #REQUIRED >

<!ATTLIST unit
	name CDATA #REQUIRED
	kind (Flow|Rain|Concentration|Volume) #REQUIRED
	value CDATA #REQUIRED >

=== christianurich/CityDrain3/data/models/test-ixxrain-dt.xml
<?xml version="1.0"?>
<!DOCTYPE citydrain SYSTEM "../dtd/model.dtd">

<citydrain version="1.0">

	<pluginpath path="nodes" />

	<simulation class="DefaultSimulation">
		<time start="1996-Jan-01 00:05:00.00" stop="1996-Jan-02 00:00:00.00" dt="300" />
		<flowdefinition>
		    <flow name="Q"/>
		    <concentration name="C0"/>
		    <concentration name="C1"/>
		    <concentration name="C2"/>
		</flowdefinition>
	</simulation>

	<model>
		<nodelist>
			<node id="rain" class="IxxRainRead">
				<parameter name="rain_file" type="string" value="data/models/Station_6620.ixx" />
			</node>
			
			<node id="fileout" class="FileOut">
				<parameter name="out_file_name" type="string" value="tmp/ixxrainout.txt" />
			</node>
			
		</nodelist>
		
		<connectionlist>
			<connection id="con1">
				<source node="rain" port="out" />
				<sink	node="fileout" port="in" />
			</connection>
		</connectionlist>
	</model>
</citydrain>

=== christianurich/CityDrain3/models/test-cycle.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE citydrain SYSTEM "file:../dtd/model.dtd">

<citydrain version="1.0">

	<pluginpath path="./libnodes.so" />
	<simulation class="DefaultSimulation">
		<time start="0" stop="7200" dt="300" />
	</simulation>
	<model>
		<nodelist>

			<node id="ConstSource-0" class="ConstSource">
				<parameter name="const_flow" kind="complex" type="Flow">
					<flow>
						<unit name="Q" kind="Flow" value="100.000000" />
						<unit name="C2" kind="Concentration" value="3.000000" />
						<unit name="C1" kind="Concentration" value="5.000000" />
						<unit name="C0" kind="Concentration" value="1.000000" />
					</flow>
				</parameter>
			</node>


			<node id="Mixer-0" class="Mixer">
				<parameter name="num_inputs" type="int" value="2" />
			</node>


			<node id="Splitter-0" class="Splitter">
				<parameter name="ratio" type="double" value="0.5" />
			</node>


			<node id="FileOut-0" class="FileOut">
				<parameter name="out_file_name" type="string" value="tmp/genout.txt" />
			</node>

		</nodelist>
		<connectionlist>

			<connection id="con-ConstSource-0-Mixer-0">
				<source node="ConstSource-0" port="out" />
				<sink node="Mixer-0" port="inputs[0]" />
			</connection>


			<connection id="con-Mixer-0-Splitter-0">
				<source node="Mixer-0" port="out" />
				<sink node="Splitter-0" port="in" />
			</connection>


			<connection id="con-Splitter-0-Mixer-0">
				<source node="Splitter-0" port="out1" />
				<sink node="Mixer-0" port="inputs[1]" />
			</connection>


			<connection id="con-Splitter-0-FileOut-0">
				<source node="Splitter-0" port="out2" />
				<sink node="FileOut-0" port="in" />
			</connection>

		</connectionlist>
	</model>
</citydrain>

=== christianurich/CityDrain3/data/models/test-catchment-ordered.xml
<?xml version="1.0"?>
<!DOCTYPE citydrain SYSTEM "../dtd/model.dtd">

<citydrain version="1.0">

	<pluginpath path="nodes" />

	<simulation class="OrderedPipeSimulation">
		<time start="0" stop="72000" dt="100" />
	</simulation>

	<model>
		<nodelist>
			<node id="rainread0" class="RainRead">
				<parameter name="file_name" type="string" value="models/Station_6620.ixx" />
			</node>
			
			<node id="fileout" class="FileOut">
				<parameter name="out_file_name" type="string" value="tmp/test-catchment-ordered.txt" />
			</node>
			
			<node id="catch" class="CatchmentCSS" />
			
			<node id="null" class="Null" />
			<node id="mixer" class="Mixer" />
		</nodelist>
		
		<connectionlist>
		
			<connection id="con0">
				<source node="rainread0" port="out" />
				<sink node="catch" port="rain_in" />
			</connection>
		
			<connection id="con2">
				<source node="null" port="out" />
				<sink node="catch" port="dwf_in" />
			</connection>
			
			<connection id="con3">
				<source node="null" port="out" />
				<sink node="catch" port="parasite_in" />
			</connection>
			
			<connection id="con4">
				<source node="null" port="out" />
				<sink node="catch" port="q_upstream" />
			</connection>
		
			<connection id="con1">
				<source node="catch" port="out" />
				<sink	node="mixer" port="inputs[0]" />
			</connection>
			
			<connection id="con5">
				<source node="catch" port="out" />
				<sink	node="mixer" port="inputs[1]" />
			</connection>
			
			<connection id="con6">
				<source	node="mixer" port="out" />
				<sink	node="fileout" port="in" />
			</connection>
		</connectionlist>
	</model>
</citydrain>

=== christianurich/CityDrain3/data/models/test-sewer-dt.xml
<?xml version="1.0"?>
<!DOCTYPE citydrain SYSTEM "../dtd/model.dtd">

<citydrain version="1.0">

	<pluginpath path="nodes" />

	<simulation class="DefaultSimulation">
		<time start="2009-Jan-01 00:00:00.00" stop="2010-Jan-01 00:00:00.00" dt="300" />
		<flowdefinition>
		    <flow name="Q"/>
		    <concentration name="C0"/>
		    <concentration name="C1"/>
		    <concentration name="C2"/>
		</flowdefinition>
	</simulation>

	<model>
		<nodelist>
			<node id="constsource" class="ConstSource">
				<parameter name="const_flow" kind="complex" type="Flow">
					<flow>
						<unit name="Q" value="234.0" />
						<unit name="C0" value="0.1"/>
						<unit name="C1" value="0.2"/>
						<unit name="C2" value="0.3" />
					</flow>
				</parameter>
			</node>
			
			<node id="fileout" class="FileOut">
				<parameter name="out_file_name" type="string" 
											value="tmp/sewerout.txt" />
			</node>
			
			<node id="musk1" class="Sewer" />
			
		</nodelist>
		
		<connectionlist>
		
			<connection id="con1">
				<source node="constsource" port="out" />
				<sink	node="musk1" port="in" />
			</connection>
			
			<connection id="con2">
				<source node="musk1" port="out" />
				<sink node="fileout" port="in" />
			</connection>
			
		</connectionlist>
	</model>
</citydrain>

=== christianurich/CityDrain3/models/paper/long-10-ordered.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE citydrain SYSTEM "file:../dtd/model.dtd">

<citydrain version="1.0">

	<pluginpath path="./libnodes.so" />
	<simulation class="OrderedPipeSimulation">
		<time start="0" stop="7200" dt="300" />
	</simulation>
	<model>
		<nodelist>

			<node id="ConstSource-0" class="ConstSource">
				<parameter name="const_flow" kind="complex" type="Flow">
					<flow>
						<unit name="Q" kind="Flow" value="100.000000" />
						<unit name="C2" kind="Concentration" value="3.000000" />
						<unit name="C1" kind="Concentration" value="5.000000" />
						<unit name="C0" kind="Concentration" value="1.000000" />
					</flow>
				</parameter>
			</node>


			<node id="Sewer-0" class="Sewer">
				<parameter name="N" type="int" value="11" />
				<parameter name="K" type="int" value="300" />
				<parameter name="X" type="double" value="0.1" />
			</node>


			<node id="Sewer-1" class="Sewer">
				<parameter name="N" type="int" value="11" />
				<parameter name="K" type="int" value="300" />
				<parameter name="X" type="double" value="0.1" />
			</node>


			<node id="Sewer-2" class="Sewer">
				<parameter name="N" type="int" value="11" />
				<parameter name="K" type="int" value="300" />
				<parameter name="X" type="double" value="0.1" />
			</node>


			<node id="Sewer-3" class="Sewer">
				<parameter name="N" type="int" value="11" />
				<parameter name="K" type="int" value="300" />
				<parameter name="X" type="double" value="0.1" />
			</node>


			<node id="Sewer-4" class="Sewer">
				<parameter name="N" type="int" value="11" />
				<parameter name="K" type="int" value="300" />
				<parameter name="X" type="double" value="0.1" />
			</node>


			<node id="Sewer-5" class="Sewer">
				<parameter name="N" type="int" value="11" />
				<parameter name="K" type="int" value="300" />
				<parameter name="X" type="double" value="0.1" />
			</node>


			<node id="Sewer-6" class="Sewer">
				<parameter name="N" type="int" value="11" />
				<parameter name="K" type="int" value="300" />
				<parameter name="X" type="double" value="0.1" />
			</node>


			<node id="Sewer-7" class="Sewer">
				<parameter name="N" type="int" value="11" />
				<parameter name="K" type="int" value="300" />
				<parameter name="X" type="double" value="0.1" />
			</node>


			<node id="Sewer-8" class="Sewer">
				<parameter name="N" type="int" value="11" />
				<parameter name="K" type="int" value="300" />
				<parameter name="X" type="double" value="0.1" />
			</node>


			<node id="Sewer-9" class="Sewer">
				<parameter name="N" type="int" value="11" />
				<parameter name="K" type="int" value="300" />
				<parameter name="X" type="double" value="0.1" />
			</node>


			<node id="FileOut-0" class="FileOut">
				<parameter name="out_file_name" type="string" value="tmp/longsewerout.txt" />
			</node>

		</nodelist>
		<connectionlist>

			<connection id="con-ConstSource-0-Sewer-0">
				<source node="ConstSource-0" port="out" />
				<sink node="Sewer-0" port="in" />
			</connection>


			<connection id="con-Sewer-0-Sewer-1">
				<source node="Sewer-0" port="out" />
				<sink node="Sewer-1" port="in" />
			</connection>


			<connection id="con-Sewer-1-Sewer-2">
				<source node="Sewer-1" port="out" />
				<sink node="Sewer-2" port="in" />
			</connection>


			<connection id="con-Sewer-2-Sewer-3">
				<source node="Sewer-2" port="out" />
				<sink node="Sewer-3" port="in" />
			</connection>


			<connection id="con-Sewer-3-Sewer-4">
				<source node="Sewer-3" port="out" />
				<sink node="Sewer-4" port="in" />
			</connection>


			<connection id="con-Sewer-4-Sewer-5">
				<source node="Sewer-4" port="out" />
				<sink node="Sewer-5" port="in" />
			</connection>


			<connection id="con-Sewer-5-Sewer-6">
				<source node="Sewer-5" port="out" />
				<sink node="Sewer-6" port="in" />
			</connection>


			<connection id="con-Sewer-6-Sewer-7">
				<source node="Sewer-6" port="out" />
				<sink node="Sewer-7" port="in" />
			</connection>


			<connection id="con-Sewer-7-Sewer-8">
				<source node="Sewer-7" port="out" />
				<sink node="Sewer-8" port="in" />
			</connection>


			<connection id="con-Sewer-8-Sewer-9">
				<source node="Sewer-8" port="out" />
				<sink node="Sewer-9" port="in" />
			</connection>


			<connection id="con-Sewer-9-FileOut-0">
				<source node="Sewer-9" port="out" />
				<sink node="FileOut-0" port="in" />
			</connection>

		</connectionlist>
	</model>
</citydrain>

=== christianurich/CityDrain3/data/models/test-array.xml
<?xml version="1.0"?>
<!DOCTYPE citydrain SYSTEM "../dtd/model.dtd">

<citydrain version="1.0">

	<pluginpath path="nodes" />

	<simulation class="DefaultSimulation">
    	<time start="0" stop="7200" dt="300" />
		<!--time start="0" stop="31556926" dt="300" /-->
		<flowdefinition>
		    <flow name="Q"/>
		    <concentration name="C0"/>
		    <concentration name="C1"/>
		    <concentration name="C2"/>
		</flowdefinition>
	</simulation>

	<model>
		<nodelist>
			<node id="constsource" class="ArrayParamTest">
				<parameter name="Qe" type="double" value="200.0" />
				<parameter name="C" kind="array" type="double">
					<arrayentry value="3.0" />
					<arrayentry value="1.2" />
					<arrayentry value="3.4" />
				</parameter>
			</node>
			
			<node id="fileout" class="FileOut">
				<parameter name="out_file_name" type="string" value="tmp/arrayout.txt" />
			</node>
			
			<node id="musk1" class="Sewer" />
			
		</nodelist>
		
		<connectionlist>
		
			<connection id="con1">
				<source node="constsource" port="out" />
				<sink	node="musk1" port="in" />
			</connection>
			
			<connection id="con2">
				<source node="musk1" port="out" />
				<sink node="fileout" port="in" />
			</connection>
			
		</connectionlist>
	</model>
</citydrain>

=== christianurich/CityDrain3/models/test-state.xml
<?xml version="1.0"?>
<!DOCTYPE citydrain SYSTEM "model.dtd">

<citydrain version="1.0">

	<pluginpath path="nodes/libnodes.so.1.0.0" />

	<simulation class="DefaultSimulation">
		<time start="0" stop="7200" dt="300" />
	</simulation>

	<model>
		<nodelist>
			<node id="constsource" class="ConstSource">
				<parameter name="const_flow" kind="complex" type="Flow">
					<flow>
						<unit name="Q" kind="Flow" value="1.0" />
						<unit name="C0" kind="Concentration" value="0.1"/>
						<unit name="C1" kind="Concentration" value="0.2"/>
					</flow>
				</parameter>
			</node>
			
			<node id="test" class="TestNode" />
			
			<node id="fileout" class="FileOut">
				<parameter name="out_file_name" type="string" value="tmp/stateout.txt" />
			</node>
			
			<node id="musk1" class="Sewer">
				<parameter name="N" type="int" value="3" />
			</node>
			
		</nodelist>
		
		<connectionlist>
		
			<connection id="con1">
				<source node="constsource" port="out" />
				<sink	node="test" port="in" />
			</connection>
			
			<connection id="con3">
				<source node="test" port="out" />
				<sink	node="musk1" port="in" />
			</connection>
			
			<connection id="con2">
				<source node="musk1" port="out" />
				<sink node="fileout" port="in" />
			</connection>
			
		</connectionlist>
	</model>
</citydrain>

=== christianurich/CityDrain3/data/models/test-qjs.xml
<?xml version="1.0"?>
<!DOCTYPE citydrain SYSTEM "model.dtd">

<citydrain version="1.0">

	<pluginpath path="nodes" />

	<simulation class="DefaultSimulation">
		<time start="0" stop="7200" dt="300" />
	</simulation>

	<model>
		<nodelist>
			<node id="constsource" class="ConstSource">
				<parameter name="const_flow" kind="complex" type="Flow">
					<flow>
						<unit name="Q" kind="Flow" value="3.0" />
						<unit name="C0" kind="Concentration" value="0.1"/>
						<unit name="C1" kind="Concentration" value="0.2"/>
					</flow>
				</parameter>
			</node>
			
			<node id="fileout1" class="FileOut">
				<parameter name="out_file_name" type="string" 
						value="tmp/jssplitter1.txt" />
			</node>
			
			<node id="fileout2" class="FileOut">
				<parameter name="out_file_name" type="string" 
						value="tmp/jssplitter2.txt" />
			</node>
			<node id="splitter" class="QSWNode" script="scripts/jssplitter.js">
			</node>
			
		</nodelist>
		
		<connectionlist>
		
			<connection id="con1">
				<source node="constsource" port="out" />
				<sink	node="splitter" port="in" />
			</connection>
			
			<connection id="con2">
				<source node="splitter" port="out1" />
				<sink node="fileout1" port="in" />
			</connection>
			
			<connection id="con3">
				<source node="splitter" port="out2" />
				<sink node="fileout2" port="in" />
			</connection>

		</connectionlist>
	</model>
</citydrain>
